FROM archlinux
RUN pacman --noconfirm -Sy rustup cargo-edit qemu-system-aarch64 aarch64-linux-gnu-gdb gcc git
RUN rustup default stable
RUN cargo install cargo-binutils
RUN rustup component add llvm-tools-preview